#!/usr/bin/env bash
# Google Search for CLI

# Usage:
#     g SEARCH_QUERY

# Adapted from http://superuser.com/a/47216

g() {
    search=""
    for term in $@; do
        search="$search$term%20"
    done
    if [ "$(uname)" == "Darwin" ]; then
        open "http://www.google.com/search?q=$search"
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        xdg-open "http://www.google.com/search?q=$search"
    else
        echo "Your OS is not supported :("
    fi
}