#!/usr/bin/env bash
# Google Search for CLI

# Usage:
#     g SEARCH_QUERY

# Adapted from http://superuser.com/a/47216

search=""
queryInit="http://www.google.com/search?q="

for term in $@; do
    search="$search$term%20"
done

if [ "$(uname)" == "Darwin" ]; then
    open "$queryInit$search"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    xdg-open "$queryInit$search"
else
    echo "Your OS is not supported :(. Only Linux and Mac are supported."
fi
